name: multi_value_listenable_builder_typed
description: A Flutter package which allows to listening to multiple ValueListenables using a single widget.
version: 0.1.1
homepage: https://github.com/LahaLuhem/multi-value-listenable-builder_typed

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
